#!/bin/bash

clear
#installation commands
echo -e '\e[0;35m+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+\e[00m';
echo -e '\033[1;34m  SUBSCRIBE MY YOUTUBE CHANNEL   \033[0m';
echo -e '\033[1;34m  youtube.com/linuxinetyt   \033[0m';
echo -e '\e[0;35m+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+\e[00m';

echo -e "\e[1;34m[*] \033[32mInstalling dependencies...... \033[0m";

echo -e '\033[1;34m SUBSCRIBE MY YOUTUBE CHANNEL FOR MORE UNIQUE VIDEOS\033[0m' ;
echo -e '\033[1;34m  youtube.com/linuxinetyt   \033[0m';

am start -a android.intent.action.VIEW -d https://youtube.com/linuxinetyt &> /dev/null ;

apt update -y &> /dev/null; apt upgrade  &> /dev/null;

pkg insall wget openssl-tool proot -y;

echo -e "\e[1;34m[*] \033[32m[*] Downloading..please wait......... \033[0m";

wget https://raw.githubusercontent.com/EXALAB/Anlinux-Resources/master/Scripts/Installer/Ubuntu/ubuntu.sh;

chmod 755 ubuntu.sh;

./ubuntu.sh;

echo -e "\e[1;34m[*] \033[32mHope you like my work..\033[0m";

echo -e "\e[1;34m[*] \033[32m Done...now run ./start-ubuntu.sh \033[0m"
